baseURL = "//www.applyboard.com/"
languageCode = "en-us"
title = "Welcome to ApplyBoard Cloud (ABC) DevOps"
publishDir = "public"
theme = "hugo-now"
#themesDir = "themes/"
# google analytics
GoogleAnalytics = "UA-XXXXXX"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Awesome DevOps"
  author = "Hugo Now"
  keywords = ["hugo-now", "hugo"]
  avatar = "/images/AB.jpg"
  displayauthor = false
  # pygments
  PygmentsUseClasses = true
  PygmentsCodeFences = true
  # pagination
  paginate = 10
  paginatePath = "page"