name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Deploy hugo site
        uses: maxheld83/ghpages@master
        env:
          HUGO_VERSION: 0.58.2
          TARGET_REPO: ApplyBoard/ab-hugo
          TOKEN: ${{ secrets.TOKEN }}
