name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the hugo site
        uses: jayat-ab/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: latest
          TARGET_REPO: ApplyBoard/ab-hugo
          TOKEN: ${{ secrets.TOKEN }}
