name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          submodules: true
      
      - name: Reattach HEAD
        run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"

      - name: Deploy the hugo site
        uses: jayat-ab/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.58.2
          TARGET_REPO: ApplyBoard/ab-hugo
          TOKEN: ${{ secrets.TOKEN }}
