name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Execute deploy script
        run: deploy.sh
