name: Push to GitHub Pages on push to master
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Deploy the hugo site
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
         ACTIONS_DEPLOY_KEY: ${{ secrets.TOKEN }}
         PUBLISH_BRANCH: master
         PUBLISH_DIR: ./public
